import Head from 'next/head';
import Card from '../components/card';
import styles from '../styles/form.module.css';
import Link from 'next/link';
import NumberInput from '../components/numberInput';
import { useState } from 'react';

export default function Form() {
  const [qtdDoors, setQtdDoors] = useState(3);

  return (
    <div className={styles.form}>
      <Head>
        <title>Monty Hall</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Card bgcolor="#c0392c">
          <h1>Monty Hall</h1>
        </Card>
        <Card>
          <NumberInput
            value={qtdDoors}
            onChange={(newQtd) => setQtdDoors(newQtd)}
            text="Quantidade de Portas?"
          />
        </Card>
      </div>
      <div>
        <Card><span className={styles.message}>Encontre a porta premiada e ganhe o Jogo</span></Card>
        <Card bgcolor="#28a085">
          <Link href={`/game/${qtdDoors}`}>
            <h2 className={styles.link}>Iníciar</h2>
          </Link>
        </Card>
      </div>
    </div>
  );
}
