import Head from 'next/head'
import Door from '../components/door'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Monty Hall</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Door />
    </div>
  )
}
