import Head from 'next/head'
import { useState } from 'react';
import Door from '../components/door'
import DoorModel from '../model/door'


export default function Home() {
  const [door, setDoor] = useState(new DoorModel(1));
  
  return (
    <div style={{display: "flex"}}>
      <Head>
        <title>Monty Hall</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Door value={door} onChange={newDoor => setDoor(newDoor)} />
    </div>
  )
}
