import Head from 'next/head';
import { useState } from 'react';
import Door from '../components/door';
import { createDoors, updateDoors } from '../functions/doors';
import DoorModel from '../model/door';

export default function Home() {
  const [doors, setDoors] = useState(createDoors(3, 2));

  const renderDoors = () => {
    return doors.map((door) => {
      return (
        <Door
          key={door.number}
          value={door}
          onChange={newDoor => setDoors(updateDoors(doors, newDoor))}
        />
      );
    });
  };

  return (
    <div style={{ display: 'flex' }}>
      <Head>
        <title>Monty Hall</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {renderDoors()}
    </div>
  );
}
