import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Monty Hall</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

    </div>
  )
}
